# Project information
site_name: Research Journal
site_description: My Personal Research Journal
site_author: J. Emmanuel Johnson
site_url: https://jejjohnson.github.io/research_journal

# Repository
repo_name: jejjohnson/research_journal
repo_url: https://github.com/jejjohnson/research_journal

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: source code pro
    code: source code pro

plugins:
  - search
  - mknotebooks:
      execute: false
      write_markdown: true
      timeout: 600

# Copyright
copyright: Copyright &copy; 2020 J. Emmanuel Johnson

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - admonition
  - pymdownx.tilde
  - pymdownx.superfences    # Adds support for nested blocks
  - pymdownx.arithmatex     # Adss support for mathjax
  - pymdownx.details        # adds support for collapsible blocks
  - pymdownx.tabbed         # enables tabbed code blocks
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true 
  - pymdownx.betterem:
      smart_enable: all
  - meta                    # enables meta data at the top of document
  - toc:
      permalink: True
  # - pymdownx.inlinehilite
  # - markdown.extensions.attr_list
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  
  # - pymdownx.smartsymbols
  # - pymdownx.tasklist:
  #     custom_checkbox: true 
  # - pymdownx.tilde

extra_javascript:
    # - https://polyfill.io/v3/polyfill.min.js?features=es6
    # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  # disqus: XHR39t5kZv
  social:
    # - type: 'envelope'
    #   link: 'http://www.shortwhale.com/ericmjl'
    - icon: fontawesome/brands/github
      link: 'https://github.com/jejjohnson'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/jejjohnson'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jejjohnson'
    - icon: fontawesome/solid/globe
      link: 'https://jejjohnson.netlify.com'
    
      